name: Deploy App

on:
  push:
    branches:
      - main      # Deploy to production
      - develop   # Deploy to development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build for development
        if: github.ref == 'refs/heads/develop'
        run: npm run build -- --mode development
        
      - name: Build for production
        if: github.ref == 'refs/heads/main'
        run: npm run build -- --mode production
        
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Deploy to development
        if: github.ref == 'refs/heads/develop'
        run: firebase deploy --only hosting --project development --token ${{ secrets.FIREBASE_TOKEN }}
          
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: firebase deploy --only hosting --project production --token ${{ secrets.FIREBASE_TOKEN }}

        